### PR TITLE
Subscribing to all residents so that after adding new resident it ret…

### LINKED ISSUE #379: [Resident]: Correct resident name is not displayed after adding new residency
Steps to Reproduce
1. Open the application
2. Click on Resident
3. Click on Add New Residency
4. Select new resident
5. Enter First name as" New Resident", last name, home and move in date
6. Click on Save
7. Notice, the resident name displayed is incorrect , it displays as unknown but has to be as "New Resident"

Video :https://www.loom.com/share/ba9a77c6e620457d8e2bca2e4fd7c366

### PR DESCRIPTION
**Pull request by shailee-m**
…rieved in table without a pull

closes #379

### CODE REVIEW

File: app/client/views/residents/residents.js [hunk 1]
```diff
@@ -6,6 +6,8 @@ Template.residents.onCreated(function() {
 
   // Subscribe to all homes, for data table
   templateInstance.subscribe("allHomes");
+  templateInstance.subscribe("allResidents");
```
Comment (brylie) [inline app/client/views/residents/residents.js]: I would prefer we didn't subscribe to all residents, so we only send necessary data to the client when possible. We have some views that are slow to render, due to the amount of data on the wire as our deployment grows.

Rather, consider moving the subscription to the table cell where the resident name is rendered. Add a template-level subscription to the "single resident" publication, passing in the `residentId` from the current row.

We will ne exploring server-side pagination and global client state management (e.g. Vuex) in subsequent work, where we can further optimize our views.

Comment (shailee-m) [reply app/client/views/residents/residents.js]: It is being used in enroll uses, password change and add new feeling, and it is working fine.

**Comment by brylie** [comment]
@all-contributors add
