### PR TITLE
Register New User: Making sure emails have a TLD

### LINKED ISSUE #391: [Registration]: Able to create account without proper email address
Steps to Reproduce:
1. Go to Registration Page
2. Enter Email Address ( E.g payal+user3@gmail)
3. Enter valid password
4. Enter Valid Password (again)
5. Click on Register
6. Notice, the account is successfully created.

Screenshot : http://prntscr.com/nl12rp

### PR DESCRIPTION
**Pull request by shailee-m**
closes #391 

Meteor by default accepts email addresses without TLD (i.e. .[com]|[in] etc.). Adding a validation method so that email addresses without TLD are not accepted.

### CODE REVIEW

File: app/lib/accounts.js [hunk 1]
```diff
@@ -16,6 +16,25 @@ AccountsTemplates.configureRoute("forgotPwd");
...
 AccountsTemplates.configureRoute("signIn");
 
-Meteor.startup(function() {
+Meteor.startup(function () {
+  Accounts.validateNewUser(function (user) {
+    if (!user) return false
+    if (!user.emails || (!!user.emails && user.emails.length === 0)) return false
+    const emailValidationRegex = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
+    /* Iterates through all emails and checks if all emails are valid */
+    const areAllEmailsValid = user.emails.every(emailObject => {
```
Comment (brylie) [inline app/lib/accounts.js]: Lets try to use Simple Schema here, so the code is less verbose.

https://github.com/aldeed/simple-schema-js/blob/master/README.md#validate-an-array-of-objects-and-throw-an-error

https://github.com/aldeed/simple-schema-js/blob/master/README.md#regex

**Comment by brylie** [comment]
This looks good. Ready to merge?

**Comment by shailee-m** [comment]
> This looks good. Ready to merge?

Yes
